### ISSUE TITLE
ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by Utlamo** [LinusPotocnik/ExampleBot#43]
Hello i am try back do discord.js and try learn V14
I npm install discord.js fs dotenv.
I catch error on start: **fs is not defined** 
if i change:
_import fs from 'fs';_
as
_import {fs} from 'fs';_
i get error:
**SyntaxError: The requested module 'fs' does not provide an export named 'fs'**
How to fix this? Can you help me?

**Comment by LinusPotocnik** [comment]
There is nothing wrong with the import in the `Bot.js` file, so changing that isn't the way to go. Instead, I simply forgot to import the `fs` module when porting my `interactionCreate` event handler from my other bot. 

To fix the issue, you simply have to put 
```js
import fs from 'fs';
```
at the top of the `interactionCreate.js` file. Aswell, you don't need to install fs as node already ships with it, so you can do
```
npm uninstall fs
```
as that one is the wrong module.

I fixed this and two other small issues in the latest release, so make sure to grab the latest release or to pull the latest version of the bot and run 
```
npm i
```
as I updated the discord.js dependency.

By the way,
```js
import { fs } from 'fs';
```
doesn't work as this imports an export named `fs` from the `fs` lib, but there is none. Instead, you want to import the entire module and store it in the `fs` variable, hence the syntax described prior.

**Comment by Utlamo** [comment]
ok i think i understand this now
`import { fs } from 'fs';` → load exported fs part
So this lines is same?:
```
import fs from 'fs';
import * as fs from 'fs';

```
I am fist time use **npm i**   🤩 i always seperate write npm install for all package. This option is so useful.

**Comment by LinusPotocnik** [comment]
Yes, these two lines do the same thing
